# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 二之前一的博客
email: blog@caofeng.me
description: > # this means to ignore newlines until "baseurl:"
    二之前一的博客，思考，写作，编程，技术
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.caofeng.me" # the base hostname & protocol for your site
github_username:  erzhiqianyi
twitter_username: erzhiqianyi
# google analytics 
google_analytics: 'UA-112078293-1'

# Build settings
markdown: kramdown
